[build-system]
requires = ["setuptools>=42", "wheel", "setuptools-rust"]
build-backend = "setuptools.build_meta"

[tool.black]
target-version = ["py37", "py38", "py39", "py310"]

[tool.isort]
profile = "black"
