name: Python Lint CI
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    name: Lint - Python 3.10
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install linting dependencies
        run: python -m pip install -r requirements-dev.txt
      - name: Run flake8
        run: flake8 fights tests
      - name: Run isort
        run: isort --check --diff fights tests
      - name: Run black
        run: black --check --diff fights tests
      - name: Run mypy
        run: tox -r -e typecheck
