name: Python Test CI
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Test - Python ${{ matrix.py }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        py:
          - "3.10"
          - "3.9"
          - "3.8"
          - "3.7"
    steps:
      - name: Setup Python ${{ matrix.py }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.py }}
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install test dependencies
        run: python -m pip install tox tox-gh-actions
      - name: Run tests
        run: tox
