name: Rust CI
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  rust:
    name: Rust
    runs-on: ubuntu-latest
    steps:
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install rustfmt
        run: rustup component add rustfmt
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run checks
        run: cargo check
      - name: Check formatting
        run: cargo fmt --all -- --check
      - name: Run tests
        run: cargo test
